### ISSUE TITLE
CO2 monitor don't responds.

### ISSUE THREAD

**Issue by AndriyPopovych** [vlast3k/simple-co2-monitor-fw#6]
CO2 monitor don't responds.
After few days of testing a CO2 monitor I seen a color bar that changes its colors during CO2 changes in the air. Firmware 1.2.2

After setting a ThingsPeak and WiFi settings. The color bar doesn't change there colors during time. After reflash to 1.2.2 nothing changes. Device looks like a broken.

**Comment by AndriyPopovych** [comment]
Possible to connect over usb for change settings.

**Comment by vlast3k** [comment]
can you try to reset it to factory settings via the usb connection and then let it powered on for 20 minutes to see if it will start working?

**Comment by vlast3k** [comment]
can you try to reset it to factory settings via the usb connection and then let it powered on for 20 minutes to see if it will start working?

**Comment by AndriyPopovych** [comment]
Looks like after a 15 minutes of waiting the reset to default settings is complete successfully. Thanks!

**Comment by vlast3k** [comment]
great!
The reason is that to get a clean initial state the sensor needs to have
worked for 10-15 minutes. It may have worked hours before -but once you
reset it - it does not know about this

**Comment by rfspeelpenning** [comment]
Isn't that the idea of a reset?

**Comment by vlast3k** [comment]
Yes, this is it - just wanted to clarify it again

**Comment by rfspeelpenning** [comment]
Ah yes my bad, though you were the TS.
