### ISSUE TITLE
Unable to set vAre for ThingSpeak.com

### ISSUE THREAD

**Issue by AndriyPopovych** [vlast3k/simple-co2-monitor-fw#7]
Unable to set vAre for ThingSpeak.com. vAre send a one test 456 PPM to ThingSpeak.com and nothing after about 3 hours ago. 

vAre is used without calibration. Calibration was made in the living room. CO2 level doesn't change from one green dash over time. But it is sensitive to human breath.

**Comment by vlast3k** [comment]
it should work also w/o calibration. it will simply in this case show some value ~400 ppm, as it thinks this is the base level. when you connect to it via the USB connection you should see  each 2 minutes how it tries to connect to thingspeak, can you post one or two such dumps ?

**Comment by AndriyPopovych** [comment]
After over 10 minutes from startup.
![co2](https://cloud.githubusercontent.com/assets/15966523/11333731/a3afd3be-91d8-11e5-874b-56d84694b8d2.jpg)

**Comment by vlast3k** [comment]
"TS KEY:" - this means that for some reason the Key for Thingspeak was not saved properly.
it should look something like "TS KEY:FF3351FA3"
I will have again a look on the code - in which situations this may happen. but in general if you received the test "456" it should be sufficient.
Could you please try again to enter the Thingspeak API key from the Wifi menu. And then check if this dump will show the id.
If it does not show it - then this is a bug.
Meanwhile i will also have a look

**Comment by AndriyPopovych** [comment]
This is very strange because my previous attempts fail. Now looks like a ThingsPeak reporting works for me !

---

Starting... v1.2.2
Box color is: 255
EEPROM Version: 3
WiFi Enabled
Simple CO2 Monitor. Press any key to display menu

(1) Set LED Thresholds
(w) Configure WIFI
(d) Enable display debugging info
(r) Factory Reset (no prompt!)
Select Option or (q)uit:
Exiting menu

(1) Set LED Thresholds
(w) Configure WIFI
(d) Enable display debugging info
(r) Factory Reset (no prompt!)
Select Option or (q)uit:
Exiting menu
TS KEY:
Sending to ThingSpeak

TS RES: -1

(1) Set LED Thresholds
(w) Configure WIFI
(d) Enable display debugging info
(r) Factory Reset (no prompt!)
Select Option or (q)uit:
Exiting menu

(1) Set LED Thresholds
(w) Configure WIFI
(d) Enable display debugging info
(r) Factory Reset (no prompt!)
Select Option or (q)uit:
(1) Set SSID
(2) Set Password
(3) Connect
(4) Set ThingSpeak API Key
Select Option or (q)uit:
Enter ThingSpeak Key:
Testing connection by sending 456 ppm value
TS KEY:5XDCG11************
Sending to ThingSpeak
Starting Wifi Module...
1

WIFI CONNECTED
WIFI GOT IP
AT+CIPSTART="TCP","184.106.153.149",80
CONNECT

OK
AT+CIPSEND=96

OK

> Recv 96 bytes

SEND OK

+IPD,1:4CLOSEDDone

Exiting menu
TS KEY:5XDCG11****************
Sending to ThingSpeak
Starting Wifi Module...
1

WIFI CONNECTED
WIFI GOT IP
AT+CIPSTART="TCP","184.106.153.149",80
CONNECT

OK
AT+CIPSEND=97

OK

> Recv 97 bytes

SEND OK

+IPD,1:5CLOSED
TS RES: 1
TS KEY:5XDCG11*********
Sending to ThingSpeak
Starting Wifi Module...
1

WIFI DISCONNECT
WIFI CONNECTED
WIFI GOT IP
AT+CIPSTART="TCP","184.106.153.149",80
CONNECT

OK
AT+CIPSEND=97

OK

> Recv 97 bytes

SEND OK

+IPD,1:6CLOSED
TS RES: 1

**Comment by vlast3k** [comment]
Great!

i am currently working on switching all this command line configuration to a dedicated chrome app, so perhaps it will work better then

**Comment by AndriyPopovych** [comment]
Looks like I can reproduce this issue. Today, after shutdown.

![co2 1](https://cloud.githubusercontent.com/assets/15966523/11362665/db96a828-929d-11e5-98c7-691a96ae95e4.jpg)

**Comment by vlast3k** [comment]
This is related to a Bug that I am currently fixing it. If you restart it - it should work.
The problem is on the 4th line - "No WiFi installed"
there is some logic that tries to identify if there is a Wifi Module installed or not. Sometimes it fails and the device thinks there is no Wifi. It should not happen often, but it happens now and then.
Currently i am changing this to work better, so in 1-2 days it should be fine.
Until then - restarting the device should solve it
Sorry for this

**Comment by AndriyPopovych** [comment]
I restart it several times for a long time but the problem was left anyway. Well I will wait for fixes.

**Comment by vlast3k** [comment]
Alright - so each time you get the message "No Wifi Installed" 
correct?

**Comment by AndriyPopovych** [comment]
Yes. This is a problem that I had a few days ago.

**Comment by vlast3k** [comment]
I have uploaded the new firmware. I've added there some additional debug code, so that it is easier to see where exactly the problem is.
With this new firmware there is no menu. Simply write in the console
wifi "ssid","pass"
and then
tskey 67DDDfVVV

Please give it a try and when it fails, send me the logs

**Comment by AndriyPopovych** [comment]
I do not see the characters in the console when entering commands.

![co2 2](https://cloud.githubusercontent.com/assets/15966523/11423144/945075d0-944a-11e5-8ac3-dc8c5beb7989.jpg)

TS: 0

**Comment by ripper121** [comment]
Then change the Settings in Putty to local echo _facepalm_

http://screencast.com/t/3HU0TPSYAvz

**Comment by vlast3k** [comment]
hmmm .. try to enter "proxy" (enter)
it should just connect to the wifi module.
 display some garbage and then "ready" if it does not display anything then maybe something has gone wrong and I will send you a replacement

**Comment by vlast3k** [comment]
![image](https://cloud.githubusercontent.com/assets/492455/11423739/b38c3696-944f-11e5-835e-e4c866c1559d.png)

this is how it should look like if the Wifi module is working

**Comment by AndriyPopovych** [comment]
Putty local echo is on now.

wifi "PTN PNH","somepass"<Enter>
tskey 67DDDfVVV<Enter>

A few sessions was made. After each session the device was unplugged and plugged to usb.

==================== FIRST SESSION ==============================

vAir CO2 Monitor: v1.3
Box color is: 255
EEPROM Version: 3
No WiFi installed
Simple CO2 Monitor. Press any key to display menu
wifi "PTN PNH", "
Connecting to Wifi...
Wifi module not working
Testing connection by sending 456 ppm value
TS KEY:67DDDfVVV
Sending to ThingSpeak
Starting Wifi Module...
0
Done. Please check if 456 was received.
TS KEY:67DDDfVVV
Sending to ThingSpeak
Starting Wifi Module...
0
w
TS RES: 0
ifi "PTN PNH","
Connecting to Wifi...
Wifi module not working
TS KEY:67DDDfVVV
Sending to ThingSpeak
Starting Wifi Module...
0

TS RES: 0

==================== SECOND SESSION ==============================

vAir CO2 Monitor: v1.3
Box color is: 255
EEPROM Version: 3
No WiFi installed
Simple CO2 Monitor. Press any key to display menu
ESP Proxy

==================== THIRD SESSION ==============================

vAir CO2 Monitor: v1.3
Box color is: 255
EEPROM Version: 3
No WiFi installed
Simple CO2 Monitor. Press any key to display menu
wifi "PTN PNH","somepass"
Connecting to Wifi...
Wifi module not working
Testing connection by sending 456 ppm value
TS KEY:67DDDfVVV
Sending to ThingSpeak
Starting Wifi Module...
0
Done. Please check if 456 was received.
TS KEY:67DDDfVVV
Sending to ThingSpeak
Starting Wifi Module...
0

TS RES: 0

**Comment by vlast3k** [comment]
Unfortunately it seems something is wrong with the Wifi :(
i will contact you via the kickstarter to discuss further details
